plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = "${mod_version}-mc${minecraft_version}-forge"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                universal_config {
                    source sourceSets.main
                }
            }
        }
        client {}
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    testImplementation platform('org.junit:junit-bom:5.10.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

tasks.named('jar', Jar) {
    from('LICENSE.txt') {
        into 'META-INF'
        rename { 'LICENSE_universal_config' }
    }
    manifest {
        attributes(
                'Specification-Title': mod_id,
                'Specification-Vendor': mod_authors,
                'Specification-Version': '1',
                'Implementation-Title': mod_name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': mod_authors
        )
    }
    finalizedBy 'reobfJar'
}
